pipeline {
  agent {
    docker {
      image 'node:16-alpine'
      args '--user root'  // (Optional: Run container as root to avoid permission issues)
    }
  }
  stages {
    stage('Test') {
      steps {
        sh 'node --version'
      }
    }
  }
}
